name: my_course_work
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.13
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  share_plus: ^2.0.4 # Updated to use share_plus instead of share
  sqflite: ^2.0.0+3
  path: ^1.8.0
  path_provider: ^2.0.0
  shared_preferences: ^2.0.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
